USE UniversityDB

SELECT * FROM Address
WHERE _city IN ('MOSCOW', 'ST.PETERSBURG')

SELECT * FROM Address
WHERE _street NOT IN ('NEVSKY PROSPECT', 'TSVETNOYBLVD')

SELECT * FROM Address
WHERE ID BETWEEN 1 AND 9

SELECT * FROM Address
WHERE _city LIKE '[M]%'